# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
# sphinx 的构建器配置等
sphinx:
  builder: html
  configuration: source/conf.py

#  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

# Optionally build your docs in additional formats such as PDF
# 需要预先构建的文件类型，用于下载使用
# formats:
#    - htmlzip
#    - pdf
# - epub

# Optionally set the version of Python and requirements required to build your docs
# 环境配置，如python版本，需额外下载的(第三方) python 包。
python:
  install:
    - requirements: requirements/requirements.txt
#   - requirements: other_requirement.txt

